# Generated by Django 2.0 on 2019-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='frequency',
            field=models.BigIntegerField(),
        ),
    ]
